# Generated by Django 4.2.27 on 2026-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupmapping',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark this group as primary for the user.'),
        ),
    ]
