# Generated by Django 4.2.27 on 2026-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrouprequest',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
