# Generated by Django 4.2.27 on 2026-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_request', '0002_usergrouprequest_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrouprequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
