# Generated by Django 5.0 on 2024-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group_usergroupmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
