# Generated by Django 4.2.27 on 2026-01-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usergroupmapping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroupmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergroupmapping',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroupmapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergrouprequests',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergrouprequests',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='usergrouprequests',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UserGroupMapping',
        ),
        migrations.DeleteModel(
            name='UserGroupRequests',
        ),
    ]
